remote_theme: just-the-docs/just-the-docs
title: "StratX & RouteFi"
description: "Programmable infrastructure connecting legacy and DeFi rails."
url: "https://StratX25.github.io"   # your GitHub Pages base URL
baseurl: "/StratX-Routfi"           # because you are using a project repo, not USERNAME.github.io
color_scheme: light

# Add the CSS file we made
assets:
  - "assets/css/custom.css"

# Quick navigation links in the header
aux_links:
  "Learn about StratX": "{{ site.baseurl }}/stratx/"
  "Explore RouteFi": "{{ site.baseurl }}/routefi/"
  "How It Fits Together": "{{ site.baseurl }}/architecture/"
