remote_theme: just-the-docs/just-the-docs
title: "StratX & RouteFi"
description: "Programmable infrastructure connecting legacy and DeFi rails."
url: "https://StratX25.github.io"
baseurl: "/StratX-Routfi"
color_scheme: light

# Custom CSS
assets:
  - "assets/css/style.css"

# Sidebar nav order
nav_order: 1

# Aux links (top right)
aux_links:
  "GitHub Repo":
    - "https://github.com/StratX25/StratX-Routfi"

# Collections
collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/
